with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  github.com/rzfhlv/go-task/internal/handler/login:
    interfaces:
      LoginHandler:
  github.com/rzfhlv/go-task/internal/handler/logout:
    interfaces:
      LogoutHandler:
  github.com/rzfhlv/go-task/internal/handler/register:
    interfaces:
      RegisterHandler:
  github.com/rzfhlv/go-task/internal/handler/task:
    interfaces:
      TaskHandler:
  github.com/rzfhlv/go-task/internal/usecase/login:
    interfaces:
      LoginUsecase:
  github.com/rzfhlv/go-task/internal/usecase/logout:
    interfaces:
      LogoutUsecase:
  github.com/rzfhlv/go-task/internal/usecase/register:
    interfaces:
      RegisterUsecase:
  github.com/rzfhlv/go-task/internal/usecase/task:
    interfaces:
      TaskUsecase:
  github.com/rzfhlv/go-task/internal/repository/cache:
    interfaces:
      CacheRepository:
  github.com/rzfhlv/go-task/internal/repository/task:
    interfaces:
      TaskRepository:
  github.com/rzfhlv/go-task/internal/repository/user:
    interfaces:
      UserRepository:
  github.com/rzfhlv/go-task/pkg/hasher:
    interfaces:
      HashPassword:
  github.com/rzfhlv/go-task/pkg/jwt:
    interfaces:
      JWTInterface:
  github.com/rzfhlv/go-task/pkg/middleware/auth:
    interfaces:
      AuthMiddleware: