// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockLogoutHandler is an autogenerated mock type for the LogoutHandler type
type MockLogoutHandler struct {
	mock.Mock
}

type MockLogoutHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogoutHandler) EXPECT() *MockLogoutHandler_Expecter {
	return &MockLogoutHandler_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function with given fields: e
func (_m *MockLogoutHandler) Logout(e echo.Context) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogoutHandler_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockLogoutHandler_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - e echo.Context
func (_e *MockLogoutHandler_Expecter) Logout(e interface{}) *MockLogoutHandler_Logout_Call {
	return &MockLogoutHandler_Logout_Call{Call: _e.mock.On("Logout", e)}
}

func (_c *MockLogoutHandler_Logout_Call) Run(run func(e echo.Context)) *MockLogoutHandler_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockLogoutHandler_Logout_Call) Return(err error) *MockLogoutHandler_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogoutHandler_Logout_Call) RunAndReturn(run func(echo.Context) error) *MockLogoutHandler_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogoutHandler creates a new instance of MockLogoutHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogoutHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogoutHandler {
	mock := &MockLogoutHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
