// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLogoutUsecase is an autogenerated mock type for the LogoutUsecase type
type MockLogoutUsecase struct {
	mock.Mock
}

type MockLogoutUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogoutUsecase) EXPECT() *MockLogoutUsecase_Expecter {
	return &MockLogoutUsecase_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function with given fields: ctx
func (_m *MockLogoutUsecase) Logout(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogoutUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockLogoutUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLogoutUsecase_Expecter) Logout(ctx interface{}) *MockLogoutUsecase_Logout_Call {
	return &MockLogoutUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx)}
}

func (_c *MockLogoutUsecase_Logout_Call) Run(run func(ctx context.Context)) *MockLogoutUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLogoutUsecase_Logout_Call) Return(_a0 error) *MockLogoutUsecase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogoutUsecase_Logout_Call) RunAndReturn(run func(context.Context) error) *MockLogoutUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogoutUsecase creates a new instance of MockLogoutUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogoutUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogoutUsecase {
	mock := &MockLogoutUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
