// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/rzfhlv/go-task/internal/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/rzfhlv/go-task/pkg/param"
)

// MockTaskUsecase is an autogenerated mock type for the TaskUsecase type
type MockTaskUsecase struct {
	mock.Mock
}

type MockTaskUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskUsecase) EXPECT() *MockTaskUsecase_Expecter {
	return &MockTaskUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockTaskUsecase) Create(ctx context.Context, _a1 model.Task) (model.Task, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) (model.Task, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) model.Task); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Task) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Task
func (_e *MockTaskUsecase_Expecter) Create(ctx interface{}, _a1 interface{}) *MockTaskUsecase_Create_Call {
	return &MockTaskUsecase_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockTaskUsecase_Create_Call) Run(run func(ctx context.Context, _a1 model.Task)) *MockTaskUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Task))
	})
	return _c
}

func (_c *MockTaskUsecase_Create_Call) Return(_a0 model.Task, _a1 error) *MockTaskUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskUsecase_Create_Call) RunAndReturn(run func(context.Context, model.Task) (model.Task, error)) *MockTaskUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTaskUsecase) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTaskUsecase_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskUsecase_Delete_Call {
	return &MockTaskUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskUsecase_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockTaskUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTaskUsecase_Delete_Call) Return(_a0 error) *MockTaskUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskUsecase_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockTaskUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTaskUsecase) GetByID(ctx context.Context, id int64) (model.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Task); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTaskUsecase_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskUsecase_GetByID_Call {
	return &MockTaskUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskUsecase_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTaskUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTaskUsecase_GetByID_Call) Return(_a0 model.Task, _a1 error) *MockTaskUsecase_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskUsecase_GetByID_Call) RunAndReturn(run func(context.Context, int64) (model.Task, error)) *MockTaskUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userId, _a2
func (_m *MockTaskUsecase) GetByUserID(ctx context.Context, userId int64, _a2 *param.Param) ([]model.Task, error) {
	ret := _m.Called(ctx, userId, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.Param) ([]model.Task, error)); ok {
		return rf(ctx, userId, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.Param) []model.Task); ok {
		r0 = rf(ctx, userId, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *param.Param) error); ok {
		r1 = rf(ctx, userId, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskUsecase_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockTaskUsecase_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
//   - _a2 *param.Param
func (_e *MockTaskUsecase_Expecter) GetByUserID(ctx interface{}, userId interface{}, _a2 interface{}) *MockTaskUsecase_GetByUserID_Call {
	return &MockTaskUsecase_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userId, _a2)}
}

func (_c *MockTaskUsecase_GetByUserID_Call) Run(run func(ctx context.Context, userId int64, _a2 *param.Param)) *MockTaskUsecase_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*param.Param))
	})
	return _c
}

func (_c *MockTaskUsecase_GetByUserID_Call) Return(_a0 []model.Task, _a1 error) *MockTaskUsecase_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskUsecase_GetByUserID_Call) RunAndReturn(run func(context.Context, int64, *param.Param) ([]model.Task, error)) *MockTaskUsecase_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockTaskUsecase) Update(ctx context.Context, _a1 model.Task) (model.Task, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) (model.Task, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) model.Task); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Task) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Task
func (_e *MockTaskUsecase_Expecter) Update(ctx interface{}, _a1 interface{}) *MockTaskUsecase_Update_Call {
	return &MockTaskUsecase_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockTaskUsecase_Update_Call) Run(run func(ctx context.Context, _a1 model.Task)) *MockTaskUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Task))
	})
	return _c
}

func (_c *MockTaskUsecase_Update_Call) Return(_a0 model.Task, _a1 error) *MockTaskUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskUsecase_Update_Call) RunAndReturn(run func(context.Context, model.Task) (model.Task, error)) *MockTaskUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskUsecase creates a new instance of MockTaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskUsecase {
	mock := &MockTaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
