// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockRegisterHandler is an autogenerated mock type for the RegisterHandler type
type MockRegisterHandler struct {
	mock.Mock
}

type MockRegisterHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterHandler) EXPECT() *MockRegisterHandler_Expecter {
	return &MockRegisterHandler_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: e
func (_m *MockRegisterHandler) Register(e echo.Context) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - e echo.Context
func (_e *MockRegisterHandler_Expecter) Register(e interface{}) *MockRegisterHandler_Register_Call {
	return &MockRegisterHandler_Register_Call{Call: _e.mock.On("Register", e)}
}

func (_c *MockRegisterHandler_Register_Call) Run(run func(e echo.Context)) *MockRegisterHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockRegisterHandler_Register_Call) Return(err error) *MockRegisterHandler_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegisterHandler_Register_Call) RunAndReturn(run func(echo.Context) error) *MockRegisterHandler_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegisterHandler creates a new instance of MockRegisterHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterHandler {
	mock := &MockRegisterHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
