// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockLoginHandler is an autogenerated mock type for the LoginHandler type
type MockLoginHandler struct {
	mock.Mock
}

type MockLoginHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginHandler) EXPECT() *MockLoginHandler_Expecter {
	return &MockLoginHandler_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: e
func (_m *MockLoginHandler) Login(e echo.Context) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockLoginHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - e echo.Context
func (_e *MockLoginHandler_Expecter) Login(e interface{}) *MockLoginHandler_Login_Call {
	return &MockLoginHandler_Login_Call{Call: _e.mock.On("Login", e)}
}

func (_c *MockLoginHandler_Login_Call) Run(run func(e echo.Context)) *MockLoginHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockLoginHandler_Login_Call) Return(err error) *MockLoginHandler_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginHandler_Login_Call) RunAndReturn(run func(echo.Context) error) *MockLoginHandler_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginHandler creates a new instance of MockLoginHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginHandler {
	mock := &MockLoginHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
