// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/rzfhlv/go-task/internal/model"
)

// MockLoginUsecase is an autogenerated mock type for the LoginUsecase type
type MockLoginUsecase struct {
	mock.Mock
}

type MockLoginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginUsecase) EXPECT() *MockLoginUsecase_Expecter {
	return &MockLoginUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, _a1
func (_m *MockLoginUsecase) Login(ctx context.Context, _a1 model.Login) (model.User, model.JWT, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.User
	var r1 model.JWT
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Login) (model.User, model.JWT, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Login) model.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Login) model.JWT); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Get(1).(model.JWT)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.Login) error); ok {
		r2 = rf(ctx, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLoginUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockLoginUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Login
func (_e *MockLoginUsecase_Expecter) Login(ctx interface{}, _a1 interface{}) *MockLoginUsecase_Login_Call {
	return &MockLoginUsecase_Login_Call{Call: _e.mock.On("Login", ctx, _a1)}
}

func (_c *MockLoginUsecase_Login_Call) Run(run func(ctx context.Context, _a1 model.Login)) *MockLoginUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Login))
	})
	return _c
}

func (_c *MockLoginUsecase_Login_Call) Return(_a0 model.User, _a1 model.JWT, _a2 error) *MockLoginUsecase_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLoginUsecase_Login_Call) RunAndReturn(run func(context.Context, model.Login) (model.User, model.JWT, error)) *MockLoginUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginUsecase creates a new instance of MockLoginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginUsecase {
	mock := &MockLoginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
